apiVersion: "database.arangodb.com/v1"
kind: "ArangoDeployment"
metadata:
  name: "sac"
spec:
  mode: Cluster
  agents:
    volumeClaimTemplate:
      spec:
        storageClassName: gp3
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 50Gi
  dbservers:
    volumeClaimTemplate:
      spec:
        storageClassName: gp3
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 500Gi
    count: 4
    resources:
      requests:
        cpu: 2000m
        memory: 4Gi
      limits:
        cpu: 2000m
        memory: 4Gi
  coordinators:
    resources:
      requests:
        cpu: 1000m
        memory: 2000Mi
      limits:
        cpu: 1000m
        memory: 2000Mi
    count: 4
  tls:
    caSecretName: None
  externalAccess:
    type: NodePort

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: 'internet-facing'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/target-type: 'ip'
    alb.ingress.kubernetes.io/healthcheck-path: '/_admin/server/availability'
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '90'
  name: sac-ingress
spec:
  ingressClassName: alb
  rules:
    - host: 'arango.api.encodedcc.org'
      http:
        paths:
          - path: '/'
            backend:
              service:
                name: sac-ea
                port:
                  number: 8529
            pathType: Prefix
